-- course name id descrp launch date 

create table hra.Course(
	course_id int ,
	course_name varchar(50),
	course_desc varchar(100),
	launch_date date )

alter proc usp_addingDataIntoCourse(
	
	@cId int,
	@cName varchar(50),
	@cdscp varchar(100),
	@cLaunchD date,
	@rtnMsg varchar(100) out)
	as 
	begin
	declare @rowCount int
	insert into hra.Course values(@cId , @cName, @cdscp , @cLaunchD)
	select * from hra.Course;
	set @rowCount =@@ROWCOUNT
	
	if(@@ROWCOUNT > 0)
	 set @rtnMsg ='Inserted '+ CAST(@rowCount as varchar) +'th into Course Table Successfully'
	else 
	set @rtnMsg ='Inserting into Course Table Failed'
	end

declare @msg varchar(100)
exec usp_addingDataIntoCourse 1019, 'IT Engineering (1)' , 'Powering realtime analyzing and logic building' , '2025/03/01' , @msg out
print @msg



select * from sales.order_items
select * from sales.stores
select * from production.stocks



-- Q1

create proc udp_quantityPerProduct(
@storeId int )
as
begin 

select product_id, count(quantity) as total_quatity_of_the_product from production.stocks where store_id = @storeId group by product_id
end

exec udp_quantityPerProduct 1


-- Q2
alter proc udp_OrderBySpecificCustomer
(@customerId int
)
as
begin
select customer_id, count(order_id) as total_orders_placed from sales.orders where customer_id = @customerId group by customer_id
end

exec udp_OrderBySpecificCustomer 2

-- Q3
create proc udp_ItemsInorders
as
begin
select o.order_id , oi.item_id, oi.list_price  from sales.orders o inner join sales.order_items oi on o.order_id = oi.order_id 
end

exec udp_ItemsInorders

-- Q4
create proc udp_EachOrderRevenue(
@orderId int,
@msg varchar(100) out
)as 
begin
declare @revenue decimal(10,2) 
 select @revenue =sum(isnull(list_price , 0) * quantity * (1- discount)) from sales.order_items
where order_id =@orderId 
set @msg = 'The revenue generated by the order ' + cast(@orderId as varchar)+' is : '+cast(@revenue as varchar) 

end

declare @m varchar(100)
exec udp_EachOrderRevenue 73, @m out
print @m

-- Q5
alter proc sales.usp_UpdateOrderShipping
(
    @OrderId INT,
    @ShippedDate DATE,
    @OrderStatus TINYINT
)
as
begin    
    -- Check if order exists
    if not exists (
        select 1
        from sales.orders
        where order_id = @OrderId
    )
    begin
        RAISERROR('Order ID %d does not exist.', 16, 1, @OrderId);
        return;
    end
 
    -- Update order
    update sales.orders
    set shipped_date = @ShippedDate,
        order_status = @OrderStatus
    where order_id = @OrderId;

    print 'Order shipping date and status updated successfully.';
end


exec sales.usp_UpdateOrderShipping
     @OrderId = 52,
     @ShippedDate = '2016-01-05',
     @OrderStatus = 4;


--Q6

create proc GetStockInfo
@storeid int ,
@threshold int,
@info varchar(100) out

as
begin

SELECT
    --MAX(ISNULL(s.,'') + ' / ' + ISNULL(s.phone,'')) AS contactDetails,
    COUNT(p.product_id) AS TotalProducts
FROM production.stocks AS s
INNER JOIN production.products AS p
    ON s.product_id = p.product_id
WHERE s.store_id = @storeid
and s.quantity <= @threshold;

if @@ROWCOUNT>0
set @info = 'Got the information about stock'
else
set @info = 'No information was obtained'

end;

declare @n varchar(200)

exec GetStockInfo 1,10,@n out

print @n


-- Q7

create proc production.usp_ProductDistributionSummary
(
    @ProductId int,
    @TotalGlobalStock int out
)
as
begin
    
    select
        s.store_id,
        s.store_name,
        s.city,
        s.state,
        st.quantity as InventoryQuantity
    from sales.stores s
    INNER JOIN production.stocks st
        on s.store_id = st.store_id
    where st.product_id = @ProductId;

    select
        @TotalGlobalStock = SUM(quantity)
    from production.stocks
    where product_id = @ProductId;
end;


declare @TotalStock int;

exec production.usp_ProductDistributionSummary 1, @TotalStock out
   
print 'Total Global Stock is : '+cast(@TotalStock as varchar)
