
select * from sales.orders

create function sales.udfCalNetSales(
 @quantity INT,
 @list_price DEC(10,2),
 @discount DEC(10,2)
)
returns dec(10,2) as 
begin 
return @quantity * @list_price*(1-@discount)
end

select sales.udfCalNetSales(24, 470, 0.15) as net_sales;

-- a func to return no.of orders generated by an individual staff using staff id as parameter and perticular year
-- drop function sales.udfOrderGenrateByIndvStaff
create function sales.udfOrderGenrateByIndvStaff(@staff_id int, @year int)
returns int as 
begin 
  declare @order_per_staff int =( select count(order_id) from sales.orders where year(order_date) =@year  and  staff_id = @staff_id)
return @order_per_staff 
end

select sales.udfOrderGenrateByIndvStaff(1 , 2018) as no_of_orders_generated_by_indv_staff

select * from sales.orders where staff_id=1 and year(order_date) = 2018


create function dbo.Age(@DOB date)
returns int
as 
begin 
 declare @Age int
 set @Age = datediff(year, @DOB , getdate()) 
 return @Age
 end

 select dbo.Age('2003/10/29')



 -- ============================1===========================

 create function fn_GetOrderFullfillmentStatus(@store_id int)
 returns @OrderDetails table(
 order_id int,
 customer_id int,
 order_date date,
 required_date date,
 shipped_date date,
 fulfillment_category varchar(20)
 )as 
 begin
 insert into @OrderDetails
 select order_id,customer_id,order_date,required_date,shipped_date,
 case
 when s.shipped_date > s.required_date then 'Late'
 when s.shipped_date <= s.required_date then 'On-Time'
 when getdate() > s.required_date then  'Overdue Pending'
 when getdate() <= s.required_date then  'In Progress'
 end
  from sales.orders s
  where store_id = @store_id
  return
  end

select * from fn_GetOrderFullfillmentStatus(3) 




 -- ============================2===========================

 alter function fn_getStaffOrderSummary(@start_date date, @endDate date)
 returns @StaffOrderDetails table(
staff_id int, 
total_orders int,
completed_order int,
delayed_order int ,
avgDayToComplete int

 ) as
 begin
   
   insert into @StaffOrderDetails
   select a.staff_id,
		  count(order_id) as Total_Order_handled,
		  sum( case when shipped_date is null then 0 else 1 end)as completed_order,
		  sum(case
              when shipped_date > required_date then 1 else 0
              end) as delayed_order,
		  avg(datediff(day,order_date, shipped_date)) as avg_shipment_day
	from sales.orders a
	group by staff_id
 return 
 end

 select * from fn_getStaffOrderSummary('2017/09/01' , '2018/12/30')




 -- ==================3===============

alter function fn_GetStoreFullfilledOrders (@store_id int ,@max_processing_days int)
 returns table as
 return( 
 select order_id,
 datediff(day,order_date, shipped_date) as shipped_orders from sales.orders where store_id = @store_id 
										and datediff(day,order_date, shipped_date) <= @max_processing_days and shipped_date is not null
 )
 select * from fn_GetStoreFullfilledOrders(2,2)





 -- ==========================4==============================
alter function fn_GetCustomerDelayedOrders(@customer_id int)
 returns table as
 return(
 select customer_id, order_id from sales.orders where (shipped_date > required_date or shipped_date is null) and customer_id = @customer_id
 )
 select * from  fn_GetCustomerDelayedOrders(175)


